/* 
 * Some version
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Aircon.My7LApi.RESTClient.OpenAPIDateConverter;

namespace Aircon.My7LApi.Model
{
    /// <summary>
    /// VersionAndEndpoints
    /// </summary>
    [DataContract]
    public partial class AuthDataModel : IEquatable<AuthDataModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VersionAndEndpoints" /> class.
        /// </summary>
        /// <param name="version">version.</param>
        /// <param name="endpoints">endpoints.</param>
        public AuthDataModel(AuthModel authModel = default(AuthModel))
        {
            this.AuthModel = authModel;
        }

        /// <summary>
        /// Gets or Sets Version
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public AuthModel AuthModel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VersionAndEndpoints {\n");
            sb.Append("  AuthModel: ").Append(AuthModel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthDataModel);
        }

        /// <summary>
        /// Returns true if VersionAndEndpoints instances are equal
        /// </summary>
        /// <param name="input">Instance of VersionAndEndpoints to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthDataModel input)
        {
            if (input == null)
                return false;

            return
                (
                    this.AuthModel == input.AuthModel ||
                    (this.AuthModel != null &&
                    this.AuthModel.Equals(input.AuthModel))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AuthModel != null)
                    hashCode = hashCode * 59 + this.AuthModel.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
